### ISSUE TITLE
Pls Fix this v 1.03 latest update

### ISSUE THREAD

**Issue by kristellion** [hoshomoh/All-Countries-Counties-For-WooCommerce#1]
Warning: Missing argument 1 for WC_All_Country_Counties::wc_add_counties_local_government(), called in /public_html/wp-content/plugins/All-Countries-Counties-For-WooCommerce-master/all-countries-counties-for-wc.php on line 216 and defined in /public_html/wp-content/plugins/All-Countries-Counties-For-WooCommerce-master/all-countries-counties-for-wc.php on line 95

**Comment by hoshomoh** [comment]
@kristellion Thanks for reporting this I would fix as soon as possible.

**Comment by hoshomoh** [comment]
You can pull the master and into your forked branch and let me know if this fixes your issue so we can close this out

**Comment by kristellion** [comment]
ok

**Comment by kristellion** [comment]
have u added LGA to it

**Comment by hoshomoh** [comment]
Yes. LGA's for Nigeria is supported at the moment. Let me know if the issue you initially reported has been resolved. Feel free to open another issue if you have any other question.

**Comment by hoshomoh** [comment]
I would close this now as I assume that this has been fixed. If you have any more issue kindly add a new issue.
