### ISSUE TITLE
Local Govt Error

### ISSUE THREAD

**Issue by kristellion** [hoshomoh/All-Countries-Counties-For-WooCommerce#3]
Pls work on the billing local government cos it doesn't show on the checkout page as a dropdown and when one tries to place an order it shows an error " Fill In billing local government" . Thanks

**Comment by hoshomoh** [comment]
Can I have screen shots because I tested this on various website and it works like charm.  Be sure the plugin is updated to the most recent version.

**Comment by kristellion** [comment]
i'll send it tomorrow

**Comment by hoshomoh** [comment]
@kristellion is this still valid? If i don't hear from you before the end of the week I would mark this issue as fixed

**Comment by kristellion** [comment]
det as fixed
