### ISSUE TITLE
Fatal error when installing the plugin in a fresh wordpress installation

### ISSUE THREAD

**Issue by rodmontgt** [hoshomoh/All-Countries-Counties-For-WooCommerce#7]
The plugin can be installed but can not be activated. A error message is returned as follows:
Fatal error: Can't use method return value in write context in /public_html/wp-content/plugins/all-countries-counties-for-wc/all-countries-counties-for-wc.php on line 57

Running WordPress 4.9.4 and woocommerce 3.3.4
PHP 5.4.45
MySQL 5.6.28

**Comment by rodmontgt** [comment]
I have upgraded to PHP 5.6.31 and the problem is resolved.

**Comment by hoshomoh** [comment]
What version of Wordpress did this happen on?

**Comment by hoshomoh** [comment]
Closing now. Thanks for the feedback.
